spring:
  application:
    name: consumerService
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: 65.49.222.208
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"

test:
  config:
    info: defaultGithubConfig22222
    
rabbitmq:
  config:
    ttl:
      exchange:
        name: ttlExchange
      queue:
        a:
          name: ttlQueueA
        b:
          name: ttlQueueB
        c:
          name: ttlQueueC
      routingKey:
        a: ttlRouteKeyA
        b: ttlRouteKeyB
        c: ttlRouteKeyC
    dl:
      exchange:
        name: dlExchange
      queue:
        a:
          name: dlQueueA
        b:
          name: dlQueueB
        c:
          name: dlQueueC
      routingKey:
        a: dlRouteKeyA
        b: dlRouteKeyB
        c: dlRouteKeyC
    delay:
      exchange:
        name: delayExchange
      queue:
        name: delayQueue
      routingKey: delayRoutingKey
