spring:
  application:
    name: consumerService
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: 65.49.222.208
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"

test:
  config:
    info: service1GithubConfig11111

server:
  port: 9000
