spring:
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  cloud:
    gateway:
      routes:
        - id: consumerService
          uri: lb://${spring.cloud.gateway.routes[0].id}
          predicates:
            - Path=/${spring.cloud.gateway.routes[0].id}/**
          filters:
            - RewritePath=/${spring.cloud.gateway.routes[0].id}/, /
        - id: providerService
          uri: lb://${spring.cloud.gateway.routes[1].id}
          predicates:
            - Path=/${spring.cloud.gateway.routes[1].id}/**
          filters:
            - RewritePath=/${spring.cloud.gateway.routes[1].id}/, /
