spring:
  application:
    name: mqConsumer
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: 65.49.222.208
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"

rabbitmq:
  config:
    dl:
      queue:
        a:
          name: dlQueueA
        b:
          name: dlQueueB
        c:
          name: dlQueueC
    delay:
      queue:
        name: delayQueue
