spring:
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: 65.49.222.208
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://192.168.126.128:3306/stockEngine?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    #type: com.alibaba.druid.pool.DruidDataSource
    hikari:
      maximum-pool-size: 150

  redis:
    #host: 192.168.126.128
    #password: redisPass
    #port: 6379
    cluster:
        nodes: 192.168.126.128:6379,192.168.126.128:6479,192.168.126.128:6579

mybatis:
  configuration:
    cache-enabled: true
  mapper-locations: classpath*:mapper/*.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
        show-details: always

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000

      circuitBreaker:
        enabled: true
        errorThresholdPercentage: 50
        requestVolumeThreshold: 4

      metrics:
        rollingStats:
          timeInMilliseconds: 10000

test:
  config:
    info: defaultGithubProviderConfig11111
