spring:
  application:
    name: providerService
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: 65.49.222.208
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://192.168.126.128:3306/stockEngine?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

management:
  endpoints:
    web:
      exposure:
        include: "*"

test:
  config:
    info: defaultGithubProviderConfig11111